// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBridgeInventory.Models;

namespace ShopInventory.Migrations
{
    [DbContext(typeof(ShopInventoryContext))]
    [Migration("20210618023434_EFCoreCodeFirstSample.Models.ShopInventoryContextSeed")]
    partial class EFCoreCodeFirstSampleModelsShopInventoryContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopBridgeInventory.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            AvailableQuantity = 11,
                            Category = "Electronics",
                            Color = "Black",
                            Description = "Full HD LED Smart Android TV",
                            Name = "Android TV",
                            Price = 12000m
                        },
                        new
                        {
                            ProductId = 2L,
                            AvailableQuantity = 5,
                            Category = "Electronics",
                            Color = "White",
                            Description = "HD Pin Hole Display, 16 MP Quad Rear Camera",
                            Name = "Mobile",
                            Price = 10000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
